theme: jekyll-theme-cayman
title: Olá! Sou Suelen Cássia, Fonoaudióloga & Analista Corporal
description: Te ensino a cuidar da sua mente e a ter uma comunicação eficaz em seus relacionamentos pessoais, olhando  para o formato do corpo.
github:
  is_project_page: false
google_analytics: G-8Z3NC4GSEP
