theme: jekyll-theme-cayman
title: Olá! Sou Suelen Cássia, Fonoaudióloga & Analista Corporal
description: Te ensino a comunicar com as pessoas olhando o formato do corpo delas. Autoconhecimento-Relacionamentos-Filhos
github:
  is_project_page: 
google_analytics: G-8Z3NC4GSEP
